### PR TITLE
TST: Test with new lookup tables

### LINKED ISSUE #146: Test against new TMG
### Description
Please run the test suite using the latest TMG, `4cm1612bm_tmg.fits`, delivered to CRDS on 2020-12-22.  This file contains a new index columns ("col0"), and we should make sure the inclusion of this (presumably) dummy column doesn't break stsynphot in unexpected ways.  

The corresponding TMC is `55104091m_tmc.fits`.

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to test against new tables, as requested.

Close #146 

@sean-lockwood , I don't know if simply looking at the results here is good enough for you, or you actually want these files to be part of the CI test suite. When run locally, I see failures but I think they are the usual numerical changes as INS continually updates the throughputs. Nothing crashed spectacularly. But also note that these are unit tests; they are not exhaustive but hopefully HST ETC test suite on your end will smoke out the rest. Hope you can clarify your acceptance criteria here. Thanks!

From  `/grp/redcat/trds/mtab/`:

* `4cm1612bm_tmg.fits` ➡️ `tables_tmg.fits`
* `55104091m_tmc.fits` ➡️ `tables_tmc.fits`
* `3241637sm_tmt.fits` ➡️ `tables_tmt.fits`

### CODE REVIEW

**Comment by sean-lockwood** [comment]
I was mostly concerned about the formatting change to the TMG causing errors.  Failed numerical differences are to be expected due to throughput changes in HST instruments.

**Comment by pllim** [comment]
Luckily new column didn't break the parser:

https://github.com/spacetelescope/stsynphot_refactor/blob/5a2fa008a4f2d48f768e3a3abcdc1220a313f0eb/stsynphot/stio.py#L309

And seems completely ignored by the class:

https://github.com/spacetelescope/stsynphot_refactor/blob/5a2fa008a4f2d48f768e3a3abcdc1220a313f0eb/stsynphot/tables.py#L18

**Comment by pllim** [comment]
If you are satisfied by the results here and okay with closing this PR *without* merge, then my job here is done. Please let me know. Thanks!

**Comment by sean-lockwood** [comment]
Thanks, @pllim !
I think your summary satisfies my concern.

**Review by sean-lockwood — APPROVED** [review]

**Pull request closed without merging**
